### ISSUE TITLE
[CHORE] jest

### ISSUE THREAD

**Issue by j-d-carmichael** [acr-lfr/generate-it#119]
This is currently running behind on jest 25 and still not on eslint (tslint).

Should be upgraded when someone is bored one day and finds a spare half hour.

**Comment by j-d-carmichael** [comment]
jest upgrade right now spews out a lot of this type of thing:
```
 Test functions cannot both take a 'done' callback and return something. Either use a 'done' callback, or return a promise.

```

**Comment by j-d-carmichael** [comment]
Also cleanup the readme to only state supported on node LTS instead of 

"Generate-It is an opensource project from acrontum and Liffery written in TypeScript and is tested on NodeJS 14 LTS."

**Comment by p-mcgowan** [comment]
i support this motion. would also add celebrate / joi if it's not a massive, api changing, breaking change

**Comment by j-d-carmichael** [comment]
I think the update to Joi might be a little more involved.. in fact the lint update will touch a lot of code too come to think of it. Probs should do them all 1 by 1

**Comment by p-mcgowan** [comment]
yeah for sure - will take a whack at it this week/end. I think the lint should be pretty quick, but running it will touch many files. 

If we don't have a linter in github actions, can push up the lint changes first and then submit another PR with the actual linting. 

jest update shouldnt be too bad either - might end up refactoring the tests a bit though. ideally not, but i tend to get carried away...

**Comment by j-d-carmichael** [comment]
i'll do the jest upgrade now as this was the original title of the issue :D

**Comment by j-d-carmichael** [comment]
Actually -  celebrate / joi are in the template not in the core so will raise the issue there instead

**Comment by j-d-carmichael** [comment]
https://github.com/acr-lfr/generate-it/pull/122
